# Generated by Django 4.1 on 2023-11-15 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenreModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(help_text="ジャンル", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TopicModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="作成者", max_length=16)),
                ("title", models.CharField(help_text="タイトル", max_length=32)),
                ("detail", models.CharField(help_text="詳細", max_length=100)),
                ("date", models.DateTimeField(help_text="作成日")),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bbs.genremodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ViewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="返信者", max_length=16)),
                ("text", models.CharField(help_text="返信", max_length=32)),
                ("data", models.DateTimeField(help_text="投稿日")),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bbs.topicmodel"
                    ),
                ),
            ],
        ),
    ]
