# Generated by Django 4.1 on 2023-11-18 04:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bbs", "0004_alter_viewmodel_topic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="viewmodel",
            old_name="data",
            new_name="date",
        ),
    ]
